title: TassoMaiAss
baseurl: ""
markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
exclude:
  - base.md
  - README.md
  - generate_site.py
  - models.py
  - tassomaiass.db